# Default values for 5gran.
ran:
  image:
    repository: docker.io/efatnar/ueransim
    pullPolicy: IfNotPresent
    tag: "v2.0"
  amf:
    address: 172.27.201.37
    port: 30412
  upf:
    address: 172.30.88.120
  user:
    imsi: "imsi-208930000000001"
    imei: "356938035643801"
    imeiSv: "4370816125816151"
    subscriptionKey: "465B5CE8B199B49FAA5F0A2EE238A6BC"
    opCode: "E8ED289DEBA952E4283B54E88E6183CA"
  tac: 7
