# Default values for 5gran.
ran:
  image:
    repository: docker.io/efatnar/ueransim
    pullPolicy: IfNotPresent
    tag: "v1.5"
  amf:
    address: 172.27.201.23
    port: 30412
  user:
    imsi: "imsi-208930000000001"
  tac: 7
