apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    #logger:
       #file: /var/log/open5gs/ausf.log
    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: open5gs-ausf
    nrf:
     sbi:
      name: open5gs-nrf
