apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    #logger:
       #file: /var/log/open5gs/smf.log
    parameter:
        no_ipv6: true
    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: open5gs-smf
        pfcp:
          dev: {{ .Values.k8s.interface }}
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.tuninterface }} 
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
           dev: {{ .Values.k8s.tuninterface }} 
        dns:
          - 8.8.8.8
        mtu: 1400
    nrf:
     sbi:
      name: open5gs-nrf 
    upf:
      pfcp:
        - name: open5gs-upf
          dnn: {{ .Values.dnn }}
