apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
    version: v2
data:
  upf.yaml: |
    upf:
        pfcp:
           dev: {{ .Values.k8s.tuninterface }} 
        gtpu:
           dev: {{ .Values.k8s.tuninterface }} 
        subnet:
          - addr: 10.45.0.1/16
            dnn: {{ .Values.dnn }}
