apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    #logger:
      #file: /var/log/open5gs/udm.log
    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: open5gs-udm
    nrf:
     sbi:
      name: open5gs-nrf
